/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aula.pkg18.pkg02.pkg2014;
import java.text.SimpleDateFormat;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.Timer;


import javax.swing.JOptionPane;
/**
 *
 * @author gabrielsg
 */


public class janela extends javax.swing.JFrame {
               //estanciando um novo calendáio



    /**
     * Creates new form janela
     */
    public janela() {
        initComponents();
        Timer t = new Timer(1, updateClockAction);
        t.start();
    }
    public String sexo = "";
    
        ActionListener updateClockAction = new ActionListener() {
  public void actionPerformed(ActionEvent e) {
      // Assumes clock is a custom component
      //concerter e conectar em variavel string
     SimpleDateFormat data = new SimpleDateFormat("dd/M/yyyy");
     SimpleDateFormat hora = new SimpleDateFormat("HH:mm:ss");
     String tempo = "Data: " + data.format(new Date()) + " / Hora: " + hora.format(new Date());
     lblhora.setText( tempo );

    }
};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgsexo = new javax.swing.ButtonGroup();
        pform = new javax.swing.JPanel();
        lblcidade = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        cbcidade = new javax.swing.JComboBox();
        cbestado = new javax.swing.JComboBox();
        btok = new javax.swing.JButton();
        psexo = new javax.swing.JPanel();
        rbm = new javax.swing.JRadioButton();
        rbf = new javax.swing.JRadioButton();
        pdata = new javax.swing.JPanel();
        lblhora = new javax.swing.JLabel();
        prand = new javax.swing.JPanel();
        pr = new javax.swing.JPanel();
        lr = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        marqui = new javax.swing.JMenu();
        mis = new javax.swing.JMenuItem();
        mop = new javax.swing.JMenu();
        mivt = new javax.swing.JMenuItem();
        mivs = new javax.swing.JMenuItem();
        micodrand = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulário");
        setMaximumSize(new java.awt.Dimension(399, 399));
        setMinimumSize(new java.awt.Dimension(399, 399));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        pform.setBorder(javax.swing.BorderFactory.createTitledBorder("| Formulário |"));
        pform.setLayout(null);

        lblcidade.setText("Cidade:");
        pform.add(lblcidade);
        lblcidade.setBounds(10, 120, 50, 20);

        lblnome.setText("Nome:");
        pform.add(lblnome);
        lblnome.setBounds(10, 30, 50, 16);

        lblestado.setText("Estado:");
        pform.add(lblestado);
        lblestado.setBounds(10, 80, 50, 20);
        pform.add(txtnome);
        txtnome.setBounds(70, 20, 150, 30);

        cbcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcidadeActionPerformed(evt);
            }
        });
        pform.add(cbcidade);
        cbcidade.setBounds(70, 120, 150, 20);

        cbestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione a estado...", "Minas Gerais", "São Paulo", "Rio de Janeiro" }));
        cbestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbestadoActionPerformed(evt);
            }
        });
        pform.add(cbestado);
        cbestado.setBounds(70, 80, 150, 20);

        btok.setText("Confirmar");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });
        pform.add(btok);
        btok.setBounds(40, 160, 160, 30);

        getContentPane().add(pform);
        pform.setBounds(10, 30, 230, 210);

        psexo.setBorder(javax.swing.BorderFactory.createTitledBorder("| Sexo |"));
        psexo.setLayout(null);

        bgsexo.add(rbm);
        rbm.setText("Masculino");
        rbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmActionPerformed(evt);
            }
        });
        psexo.add(rbm);
        rbm.setBounds(20, 20, 93, 21);

        bgsexo.add(rbf);
        rbf.setText("Feminino");
        rbf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbfMouseClicked(evt);
            }
        });
        psexo.add(rbf);
        rbf.setBounds(20, 40, 80, 21);

        getContentPane().add(psexo);
        psexo.setBounds(240, 40, 140, 80);

        pdata.setBorder(javax.swing.BorderFactory.createTitledBorder("| Data hora em Tempo Real |"));
        pdata.setLayout(null);

        lblhora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pdata.add(lblhora);
        lblhora.setBounds(20, 20, 300, 30);

        getContentPane().add(pdata);
        pdata.setBounds(20, 240, 330, 60);

        prand.setBorder(javax.swing.BorderFactory.createTitledBorder("| Número Aleatório |"));
        prand.setLayout(null);

        pr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pr.setLayout(null);

        lr.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lr.setText("0");
        lr.setToolTipText("");
        pr.add(lr);
        lr.setBounds(10, 10, 60, 40);

        prand.add(pr);
        pr.setBounds(30, 30, 80, 60);

        getContentPane().add(prand);
        prand.setBounds(240, 130, 140, 110);

        marqui.setText("Arquivo");

        mis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula/pkg18/pkg02/pkg2014/sair.png"))); // NOI18N
        mis.setText("Sair");
        mis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misActionPerformed(evt);
            }
        });
        marqui.add(mis);

        jMenuBar1.add(marqui);

        mop.setText("Operações");

        mivt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula/pkg18/pkg02/pkg2014/lupa.png"))); // NOI18N
        mivt.setText("Visualizar Todos");
        mivt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mivtActionPerformed(evt);
            }
        });
        mop.add(mivt);

        mivs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula/pkg18/pkg02/pkg2014/mef.png"))); // NOI18N
        mivs.setText("Visualizar Sexo");
        mivs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mivsMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mivsMouseClicked(evt);
            }
        });
        mivs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mivsActionPerformed(evt);
            }
        });
        mop.add(mivs);

        micodrand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula/pkg18/pkg02/pkg2014/rand.png"))); // NOI18N
        micodrand.setText("Gerar Número Aleatório");
        micodrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                micodrandMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                micodrandMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                micodrandMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                micodrandMouseClicked(evt);
            }
        });
        micodrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micodrandActionPerformed(evt);
            }
        });
        mop.add(micodrand);

        jMenuBar1.add(mop);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void misActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_misActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void micodrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micodrandMouseClicked
        // TODO add your handling code here:
        int num = (int) (Math.random() * 100);
        String numrand = String.valueOf( num );  
        lr.setText(numrand);
    
    }//GEN-LAST:event_micodrandMouseClicked

    private void micodrandMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micodrandMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_micodrandMouseEntered

    private void micodrandMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micodrandMousePressed
        // TODO add your handling code here:
         int num = (int) (Math.random() * 100);
        String numrand = String.valueOf( num );  
        lr.setText(numrand);
    }//GEN-LAST:event_micodrandMousePressed

    private void micodrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micodrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_micodrandActionPerformed

    private void micodrandMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micodrandMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_micodrandMouseExited

    private void rbfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbfMouseClicked
        // TODO add your handling code here:
        sexo = "Feminino";
    }//GEN-LAST:event_rbfMouseClicked

    private void rbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmActionPerformed
        // TODO add your handling code here:
        sexo = "Masculino";
    }//GEN-LAST:event_rbmActionPerformed

    private void mivsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mivsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mivsMouseClicked

    private void mivsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mivsMousePressed
        // TODO add your handling code here:
        if (!sexo.equals(""))
        {
        JOptionPane.showMessageDialog(null, "seu sexo é: " + sexo);
        }
        else
        {
        JOptionPane.showMessageDialog(null, "A opção não foi selecionada!");
        }
    }//GEN-LAST:event_mivsMousePressed

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        // TODO add your handling code here:
        String nome = txtnome.getText();
        String cidade = (String)cbcidade.getSelectedItem();
        String estado = (String)cbestado.getSelectedItem();
        if (nome.equals("") || cidade.endsWith("Selecione a cidade...") || estado.endsWith("Selecione a estado..."))
        {
            JOptionPane.showMessageDialog(null,"Aalguma das caixas não foram corretamente preenchidas");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Nome: " + nome + ".\nCidade: " + cidade + ".\nEstado: " + estado + ".");
        }
    }//GEN-LAST:event_btokActionPerformed

    private void cbestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbestadoActionPerformed
        // TODO add your handling code here:
        String estado = (String)cbestado.getSelectedItem();
        cbcidade.removeAllItems();
        if (estado.equals("Minas Gerais"))
        {
        cbcidade.addItem("Selecione a cidade...");
        cbcidade.addItem("Cataguases");
        cbcidade.addItem("Juiz de Fora");
        cbcidade.addItem("Belo Horizonte");
        }
        else if (estado.equals("São Paulo"))
        {
        cbcidade.addItem("Selecione a cidade...");
        cbcidade.addItem("São Paulo");
        cbcidade.addItem("Campinas");
        cbcidade.addItem("Bauru");
        }
        else if (estado.equals("Rio de Janeiro"))
        {
        cbcidade.addItem("Selecione a cidade...");
        cbcidade.addItem("Rio de Janeiro");
        cbcidade.addItem("Rio das Ostras");
        cbcidade.addItem("Niteroi");
        }
    }//GEN-LAST:event_cbestadoActionPerformed

    private void cbcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcidadeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                 int num = (int) (Math.random() * 100);
        String numrand = String.valueOf( num );  
        lr.setText(numrand);
       

    }//GEN-LAST:event_formWindowOpened

    private void mivtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mivtActionPerformed
        // TODO add your handling code here:
        String nome = txtnome.getText();
        String cidade = (String)cbcidade.getSelectedItem();
        String estado = (String)cbestado.getSelectedItem();
        if (nome.equals("") || cidade.endsWith("Selecione a cidade...") || estado.endsWith("Selecione a estado...") || sexo.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Aalguma das caixas não foram corretamente preenchidas");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Nome: " + nome + ".\nSexo: " + sexo + ".\nCidade: " + cidade + ".\nEstado: " + estado + ".");
        }
    }//GEN-LAST:event_mivtActionPerformed

    private void mivsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mivsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mivsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgsexo;
    private javax.swing.JButton btok;
    private javax.swing.JComboBox cbcidade;
    private javax.swing.JComboBox cbestado;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblcidade;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblhora;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lr;
    private javax.swing.JMenu marqui;
    private javax.swing.JMenuItem micodrand;
    private javax.swing.JMenuItem mis;
    private javax.swing.JMenuItem mivs;
    private javax.swing.JMenuItem mivt;
    private javax.swing.JMenu mop;
    private javax.swing.JPanel pdata;
    private javax.swing.JPanel pform;
    private javax.swing.JPanel pr;
    private javax.swing.JPanel prand;
    private javax.swing.JPanel psexo;
    private javax.swing.JRadioButton rbf;
    private javax.swing.JRadioButton rbm;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
