/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aula.pkg25.pkg05.pkg2014;

import javax.swing.JOptionPane;

/**
 *
 * @author gabrielsg
 */
public class janela extends javax.swing.JFrame {

    /**
     * Creates new form janela
     */
    public String sexo = "";
    public String curso = "";
    public String Scurso = "";
    public String Sestado = "";
    public String nome = "";
    public janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgcurso = new javax.swing.ButtonGroup();
        btgsexo = new javax.swing.ButtonGroup();
        pcad = new javax.swing.JPanel();
        lblestado = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblcurso = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        cbest = new javax.swing.JComboBox();
        cbcur = new javax.swing.JComboBox();
        btok = new javax.swing.JButton();
        btsair = new javax.swing.JButton();
        pcur = new javax.swing.JPanel();
        ckmestrado = new javax.swing.JCheckBox();
        ckdoutorado = new javax.swing.JCheckBox();
        psex = new javax.swing.JPanel();
        rbf = new javax.swing.JRadioButton();
        rbm = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mcad = new javax.swing.JMenu();
        ms = new javax.swing.JMenu();
        mc = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa 2");
        setMaximumSize(new java.awt.Dimension(473, 415));
        setMinimumSize(new java.awt.Dimension(473, 415));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        pcad.setBorder(javax.swing.BorderFactory.createTitledBorder("| Cadastro |"));
        pcad.setLayout(null);

        lblestado.setText("Estado:");
        pcad.add(lblestado);
        lblestado.setBounds(247, 90, 50, 16);

        lblnome.setText("Nome:");
        pcad.add(lblnome);
        lblnome.setBounds(10, 50, 40, 16);

        lblcurso.setText("Curso:");
        pcad.add(lblcurso);
        lblcurso.setBounds(10, 90, 40, 16);

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        pcad.add(txtnome);
        txtnome.setBounds(60, 40, 300, 30);

        cbest.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "ES", "MG", "RJ", "SP" }));
        cbest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbestActionPerformed(evt);
            }
        });
        pcad.add(cbest);
        cbest.setBounds(290, 90, 120, 22);

        cbcur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Sistema de Informação", "Ciência da Computação" }));
        cbcur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcurActionPerformed(evt);
            }
        });
        pcad.add(cbcur);
        cbcur.setBounds(50, 90, 180, 22);

        btok.setText("Mostrar");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });
        pcad.add(btok);
        btok.setBounds(60, 150, 73, 23);

        btsair.setText("Sair");
        btsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsairActionPerformed(evt);
            }
        });
        pcad.add(btsair);
        btsair.setBounds(270, 150, 72, 23);

        getContentPane().add(pcad);
        pcad.setBounds(10, 20, 450, 200);

        pcur.setBorder(javax.swing.BorderFactory.createTitledBorder("| Curso |"));
        pcur.setLayout(null);

        ckmestrado.setText("Mestrado");
        ckmestrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckmestradoActionPerformed(evt);
            }
        });
        pcur.add(ckmestrado);
        ckmestrado.setBounds(50, 20, 81, 20);

        ckdoutorado.setText("Doutorado");
        ckdoutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckdoutoradoActionPerformed(evt);
            }
        });
        pcur.add(ckdoutorado);
        ckdoutorado.setBounds(270, 20, 81, 20);

        getContentPane().add(pcur);
        pcur.setBounds(10, 290, 450, 50);

        psex.setBorder(javax.swing.BorderFactory.createTitledBorder("| Sexo |"));
        psex.setLayout(null);

        btgsexo.add(rbf);
        rbf.setText("Femonino");
        rbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfActionPerformed(evt);
            }
        });
        psex.add(rbf);
        rbf.setBounds(270, 20, 100, 21);

        btgsexo.add(rbm);
        rbm.setText("Masculino");
        rbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmActionPerformed(evt);
            }
        });
        psex.add(rbm);
        rbm.setBounds(40, 20, 100, 21);

        getContentPane().add(psex);
        psex.setBounds(10, 230, 450, 50);

        mcad.setText("Cadastro");
        mcad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mcadMouseClicked(evt);
            }
        });
        mcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcadActionPerformed(evt);
            }
        });
        jMenuBar1.add(mcad);

        ms.setText("Sexo");
        ms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msMouseClicked(evt);
            }
        });
        jMenuBar1.add(ms);

        mc.setText("Curso");
        mc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mcMouseClicked(evt);
            }
        });
        jMenuBar1.add(mc);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmActionPerformed
        // TODO add your handling code here:
        sexo = rbm.getText();
    }//GEN-LAST:event_rbmActionPerformed

    private void rbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfActionPerformed
        // TODO add your handling code here:
        sexo = rbf.getText();
    }//GEN-LAST:event_rbfActionPerformed

    private void cbcurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcurActionPerformed
        // TODO add your handling code here:
        Scurso = (String)cbcur.getSelectedItem();
        cbcur.removeItem("Selecione");
    }//GEN-LAST:event_cbcurActionPerformed

    private void cbestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbestActionPerformed
        // TODO add your handling code here:
        Sestado = (String)cbest.getSelectedItem();
        cbest.removeItem("Selecione");
    }//GEN-LAST:event_cbestActionPerformed

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        // TODO add your handling code here:
        nome = txtnome.getText();
        if (!nome.equals("") && !Sestado.equals("") && !Scurso.equals("")
                && !sexo.equals("") && !curso.equals(""))
        {
            JOptionPane.showMessageDialog (null, "Nome: " + nome
                    + ".\nEstado: " + Sestado + ".\nSexo: " + sexo
                    + ".\ncurso: " + Scurso + "\nTipo: " + curso + ".");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Preencha todas as opções para ver o resultado!");
        }
    }//GEN-LAST:event_btokActionPerformed

    private void btsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btsairActionPerformed

    private void mcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcadActionPerformed

    private void mcadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcadMouseClicked
        // TODO add your handling code here:
                nome = txtnome.getText();
        if (!nome.equals("") && !Sestado.equals("") && !Scurso.equals(""))
        {
            JOptionPane.showMessageDialog (null, "Nome: " + nome
                    + ".\nEstado: " + Sestado + ".\ncurso: " + Scurso + ".");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Preencha todas as opções para ver o resultado!");
        }
    }//GEN-LAST:event_mcadMouseClicked

    private void msMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msMouseClicked
        // TODO add your handling code here:
        if (!sexo.equals(""))
        {
            JOptionPane.showMessageDialog (null, "Sexo: " + sexo + ".");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Preencha todas as opções para ver o resultado!");
        }
    }//GEN-LAST:event_msMouseClicked

    private void mcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcMouseClicked
        // TODO add your handling code here:
        if (!curso.equals(""))
        {
            JOptionPane.showMessageDialog (null, "Cursando: " + curso + ".");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Preencha todas as opções para ver o resultado!");
        }
    }//GEN-LAST:event_mcMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void ckmestradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckmestradoActionPerformed
        // TODO add your handling code here:
       if (ckmestrado.isSelected() == true && ckdoutorado.isSelected() == true)
        {
        curso = ckmestrado.getText() + " e " + ckdoutorado.getText();
        }
       else if (ckmestrado.isSelected() == true && ckdoutorado.isSelected() == false)
        {
        curso = ckmestrado.getText();
        }
       else if (ckmestrado.isSelected() == false && ckdoutorado.isSelected() == true)
        {
        curso = ckdoutorado.getText();
        }
       else if (ckmestrado.isSelected() == false && ckdoutorado.isSelected() == false)
        {
        curso = "";
        }
    }//GEN-LAST:event_ckmestradoActionPerformed

    private void ckdoutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckdoutoradoActionPerformed
        // TODO add your handling code here:
       if (ckmestrado.isSelected() == true && ckdoutorado.isSelected() == true)
        {
        curso = ckmestrado.getText() + " e " + ckdoutorado.getText();
        }
       else if (ckmestrado.isSelected() == true && ckdoutorado.isSelected() == false)
        {
        curso = ckmestrado.getText();
        }
       else if (ckmestrado.isSelected() == false && ckdoutorado.isSelected() == true)
        {
        curso = ckdoutorado.getText();
        }
       else if (ckmestrado.isSelected() == false && ckdoutorado.isSelected() == false)
        {
        curso = "";
        }
    }//GEN-LAST:event_ckdoutoradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgcurso;
    private javax.swing.ButtonGroup btgsexo;
    private javax.swing.JButton btok;
    private javax.swing.JButton btsair;
    private javax.swing.JComboBox cbcur;
    private javax.swing.JComboBox cbest;
    private javax.swing.JCheckBox ckdoutorado;
    private javax.swing.JCheckBox ckmestrado;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblcurso;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblnome;
    private javax.swing.JMenu mc;
    private javax.swing.JMenu mcad;
    private javax.swing.JMenu ms;
    private javax.swing.JPanel pcad;
    private javax.swing.JPanel pcur;
    private javax.swing.JPanel psex;
    private javax.swing.JRadioButton rbf;
    private javax.swing.JRadioButton rbm;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
